import { SocietySummary, Society, BachelorRating, VibeCheck, RentReport, Logistics } from "@/types/society";

export const MOCK_SOCIETIES: SocietySummary[] = [
  {
    id: "demo-1",
    name: "Raheja Residency",
    slug: "raheja-residency",
    area: "Andheri West",
    address: "Plot 14, New Link Road, Andheri West",
    lat: 19.1364,
    lng: 72.8296,
    verified: true,
    bachelor_index: 7.5,
    rent_report_count: 12,
    vibe_check_count: 8,
  },
  {
    id: "demo-2",
    name: "Lodha Palava",
    slug: "lodha-palava",
    area: "Powai",
    address: "Hiranandani Gardens, Powai",
    lat: 19.1197,
    lng: 72.9051,
    verified: true,
    bachelor_index: 4.2,
    rent_report_count: 6,
    vibe_check_count: 3,
  },
  {
    id: "demo-3",
    name: "Vasant Galaxy",
    slug: "vasant-galaxy",
    area: "Goregaon West",
    address: "SV Road, Goregaon West",
    lat: 19.1663,
    lng: 72.8424,
    verified: false,
    bachelor_index: 8.9,
    rent_report_count: 4,
    vibe_check_count: 5,
  },
  {
    id: "demo-4",
    name: "Nahar Amrit Shakti",
    slug: "nahar-amrit-shakti",
    area: "Chandivali",
    address: "Chandivali Farm Road, Andheri East",
    lat: 19.1052,
    lng: 72.8891,
    verified: true,
    bachelor_index: 6.0,
    rent_report_count: 9,
    vibe_check_count: 7,
  },
  {
    id: "demo-5",
    name: "Kalpataru Aura",
    slug: "kalpataru-aura",
    area: "Bandra West",
    address: "Turner Road, Bandra West",
    lat: 19.0544,
    lng: 72.8358,
    verified: true,
    bachelor_index: 3.8,
    rent_report_count: 15,
    vibe_check_count: 11,
  },
];

export const MOCK_SOCIETY: Society = {
  id: "demo-1",
  name: "Raheja Residency",
  slug: "raheja-residency",
  address: "Plot 14, New Link Road, Andheri West",
  area: "Andheri West",
  pin_code: "400053",
  total_buildings: 4,
  total_units: 120,
  year_built: 2008,
  verified: true,
  created_at: "2026-01-15T10:00:00Z",
};

export const MOCK_BACHELOR_RATINGS: BachelorRating[] = [
  {
    id: "br-1",
    score: 8,
    notes: "Very chill society. Bachelors in most buildings, no issues.",
    created_at: "2026-04-10T10:00:00Z",
    profiles: { display_name: "Arjun M." },
  },
  {
    id: "br-2",
    score: 7,
    notes: "Building A is stricter, but B and C are fine.",
    created_at: "2026-03-22T10:00:00Z",
    profiles: { display_name: "Priya S." },
  },
  {
    id: "br-3",
    score: 8,
    notes: null,
    created_at: "2026-02-15T10:00:00Z",
    profiles: { display_name: "Rohan K." },
  },
];

export const MOCK_VIBE_CHECKS: VibeCheck[] = [
  {
    id: "vc-1",
    committee_vibe: 4,
    neighbour_vibe: 5,
    noise_level: 3,
    pet_friendly: true,
    review: "Great community! Committee is responsive. Diwali and Holi celebrations are amazing.",
    created_at: "2026-04-05T10:00:00Z",
    profiles: { display_name: "Ananya R." },
  },
  {
    id: "vc-2",
    committee_vibe: 3,
    neighbour_vibe: 4,
    noise_level: 2,
    pet_friendly: true,
    review: "Neighbours are friendly. Can be noisy on weekends due to kids playing in compound.",
    created_at: "2026-03-18T10:00:00Z",
    profiles: { display_name: "Vikram P." },
  },
  {
    id: "vc-3",
    committee_vibe: 4,
    neighbour_vibe: 4,
    noise_level: 4,
    pet_friendly: false,
    review: null,
    created_at: "2026-02-28T10:00:00Z",
    profiles: { display_name: "Sneha D." },
  },
];

export const MOCK_RENT_REPORTS: RentReport[] = [
  {
    id: "rr-1",
    flat_type: "1BHK",
    rent_monthly: 22000,
    deposit: 100000,
    maintenance_monthly: 3500,
    furnished: false,
    reported_at: "2026-04-01",
    created_at: "2026-04-01T10:00:00Z",
  },
  {
    id: "rr-2",
    flat_type: "2BHK",
    rent_monthly: 35000,
    deposit: 150000,
    maintenance_monthly: 5000,
    furnished: true,
    reported_at: "2026-03-15",
    created_at: "2026-03-15T10:00:00Z",
  },
  {
    id: "rr-3",
    flat_type: "2BHK",
    rent_monthly: 32000,
    deposit: 130000,
    maintenance_monthly: 5000,
    furnished: false,
    reported_at: "2026-02-20",
    created_at: "2026-02-20T10:00:00Z",
  },
  {
    id: "rr-4",
    flat_type: "3BHK",
    rent_monthly: 55000,
    deposit: 250000,
    maintenance_monthly: 7500,
    furnished: true,
    reported_at: "2026-01-10",
    created_at: "2026-01-10T10:00:00Z",
  },
];

export const MOCK_LOGISTICS: Logistics = {
  nearest_metro: "D.N. Nagar Metro",
  metro_distance_km: 0.8,
  nearest_railway: "Andheri Station",
  railway_distance_km: 1.5,
  water_reliability: 4,
  power_backup: true,
  nearby_essentials: ["D-Mart", "Zepto Hub", "Vegetable Market", "Medical Store", "HDFC ATM"],
};
